Use an environment file for configuration.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -2,10 +2,15 @@
 
 cd `dirname "$0"`/..
 
-# Aggregate build step exit codes.
+# Exit on errors
 exit_code=0
-trap '(( exit_code |= $? ))' ERR
+trap 'exit $?' ERR
 
+if [ ! -f ./.env ]; then
+    cp ./.env.dist ./.env
+    echo "Maison is being built for the first time. Update the configuration at `readlink -f ./.env` and run this command (./bin/build) again to finish the build."
+    exit 1
+fi
 mkdir -p ./db/data
 mkdir -p ./network/data
 touch ./nginx/htpasswd
