Deploy Alfred.

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -2,9 +2,26 @@
 
 cd `dirname "$0"`/..
 
+# Aggregate test exit codes.
+exit_code=0
+trap '(( exit_code |= $? ))' ERR
+
 ./bin/build
 ./bin/run
+sleep 1
 
+curl http://localhost:8081/about/json/schema
 curl http://localhost:8080
 
 ./bin/stop
+
+# Stop aggregating test exit codes.
+trap - ERR
+
+if [ $exit_code -eq 0 ]
+then
+    echo "SUCCESS: ALL TESTS PASSED."
+else
+    echo "ERROR: SOME TESTS FAILED."
+fi
+exit $exit_code
